package com.karyadi.skripsi.model

import android.os.Parcelable
import kotlinx.android.parcel.Parcelize

@Parcelize
data class DetailPesanan(
    val alamat_pelanggan: String?,
    val alamat_tukang: String?,
    val asal_bahan: String?,
    val bahan_tukang: String?,
    val biaya_tukang: Int?,
    val catatan_pesanan: String?,
    val desain_tukang: String?,
    val email_pelanggan: String?,
    val email_tukang: String?,
    val foto_pelanggan: String?,
    val foto_tukang: String?,
    val gambar_kategori: String?,
    val harga_bahan: Int?,
    val hari_buka: String?,
    val id_detail_kategori: Int?,
    val id_kategori: Int?,
    val id_pelanggan: Int?,
    val id_tukang: Int?,
    val id_pesanan: Int?,
    val jam_buka: String?,
    val jam_tutup: String?,
    val jangkauan_kategori_tukang: String?,
    val jk_pelanggan: String?,
    val jumlah_tukang: Int?,
    val keterangan_kategori: String?,
    val keterangan_toko: String?,
    val lama_waktu_pengerjaan: String?,
    val latitude_pelanggan: String?,
    val latitude_tukang: String?,
    val lebar_bahan: Int?,
    val longitude_pelanggan: String?,
    val longitude_tukang: String?,
    val nama_kategori: String?,
    val nama_pelanggan: String?,
    val nama_tukang: String?,
    val nama_toko: String?,
    val ongkos_tukang: Int?,
    val panjang_bahan: Int?,
    val password_pelanggan: String?,
    val password_tukang: String?,
    val perkiraan_lama_waktu_pengerjaan: String?,
    val spesifikasi_tukang: String?,
    val status_bahan: String?,
    val status_pesanan: String?,
    val tanggal_pesanan: String?,
    val tanggal_pesanan_selesai: String?,
    val telp_pelanggan: String?,
    val telp_tukang: String?,
    val total_biaya: Int?
) : Parcelable