package com.karyadi.skripsi.utils

object Constant {

//    const val BASE_URL = "https://tukangapi.000webhostapp.com"
//    const val BASE_URL = "https://adminapitukang.000webhostapp.com/"
//    const val BASE_URL = "https://apitukangbangun.000webhostapp.com/"
    const val BASE_URL = "https://www.tukang-bangunan.my.id/"

    //    const val BASE_URL = "http://192.168.0.104:8000/"
    const val PATH_API = "api"

    const val IMAGE_TUKANG = "https://tukang-bangunan.my.id/img_tukang/"
    const val IMAGE_PELANGGAN = "https://tukang-bangunan.my.id/img_pelanggan/"
    const val IMAGE_KATEGORI = "https://tukang-bangunan.my.id/img_kategori/"
    const val IMAGE_UKURAN = "https://adminapitukang.000webhostapp.com/img_ukuran/"

    const val PATH_DETAIL_KATEGORI = "/detail_kategori"
    const val PATH_GET_TUKANG = "/get_tukang"
    const val PATH_GET_KATEGORI = "/get_kategori"
    const val PATH_GET_DETAIL_KATEGORI = "/get_detail_kategori"
    const val PATH_DETAIL_PESANAN = "/detail_pesanan"
    const val PATH_KATEGORI = "/kategori"
    const val PATH_PELANGGAN = "/pelanggan"
    const val PATH_ID_PELANGGAN = "/{id_pelanggan}"
    const val PATH_TUKANG = "/tukang"
    const val PATH_ID_TUKANG = "/{id_tukang}"
    const val PATH_ID_KATEGORI = "/{id_kategori}"
    const val PATH_ID_DETAIL_KATEGORI = "/{id_detail_kategori}"
    const val PATH_ID_UKURAN_DETAIL_KATEGORI = "/{id_ukuran_detail_kategori}"
    const val PATH_ID_UKURAN_DETAIL_PESANAN = "/{id_ukuran_detail_pesanan}"
    const val PATH_ID_PESANAN = "/{id_pesanan}"
    const val PATH_NILAI = "/nilai"
    const val PATH_PESANAN = "/pesanan"
    const val PATH_RATING = "/rating"
    const val PATH_UKURAN = "/ukuran"
    const val PATH_UTILITAS = "/utilitas"
    const val PATH_UKURAN_DETAIL_KATEGORI = "/ukuran_detail_kategori"
    const val PATH_UKURAN_DETAIL_PESANAN = "/ukuran_detail_pesanan"

    const val PATH_INSERT_DATA = "/insert_data"
    const val PATH_UPDATE = "/update"
    const val PATH_DELETE = "/delete"

    const val PATH_PILIH_JENIS ="/pilihjenis"
    const val URL_PILIH_JENIS ="$PATH_API$PATH_PILIH_JENIS"

    const val URL_DETAIL_KATEGORI_GET = "$PATH_API$PATH_DETAIL_KATEGORI"
    const val URL_DETAIL_KATEGORI_GET_BY_TUKANG = "$PATH_API$PATH_DETAIL_KATEGORI$PATH_GET_TUKANG$PATH_ID_TUKANG"
    const val URL_DETAIL_KATEGORI_INSERT = "$PATH_API$PATH_DETAIL_KATEGORI$PATH_INSERT_DATA"
    const val URL_DETAIL_KATEGORI_UPDATE = "$PATH_API$PATH_DETAIL_KATEGORI$PATH_UPDATE$PATH_ID_DETAIL_KATEGORI"
    const val URL_DETAIL_KATEGORI_DELETE = "$PATH_API$PATH_DETAIL_KATEGORI$PATH_DELETE$PATH_ID_DETAIL_KATEGORI"
//    https://tukangapi.000webhostapp.com/api/detail_kategori/get_kategori/2
    const val URL_DETAIL_KATEGORI_GET_BY_KATEGORI = "$PATH_API$PATH_DETAIL_KATEGORI$PATH_GET_KATEGORI$PATH_ID_KATEGORI"

    const val URL_DETAIL_PESANAN_GET = "$PATH_API$PATH_DETAIL_PESANAN"
    const val URL_DETAIL_PESANAN_INSERT = "$PATH_API$PATH_DETAIL_PESANAN$PATH_INSERT_DATA"
    const val URL_DETAIL_PESANAN_UPDATE = "$PATH_API$PATH_DETAIL_PESANAN$PATH_UPDATE"
    const val URL_DETAIL_PESANAN_DELETE = "$PATH_API$PATH_DETAIL_PESANAN$PATH_DELETE"

    const val URL_KATEGORI_GET = "$PATH_API$PATH_KATEGORI"
    const val URL_KATEGORI_INSERT = "$PATH_API$PATH_KATEGORI$PATH_INSERT_DATA"
    const val URL_KATEGORI_UPDATE = "$PATH_API$PATH_KATEGORI$PATH_UPDATE"
    const val URL_KATEGORI_DELETE = "$PATH_API$PATH_KATEGORI$PATH_DELETE"

    const val URL_PELANGGAN_GET = "$PATH_API$PATH_PELANGGAN"
    const val URL_PELANGGAN_GET_BY_ID = "$PATH_API$PATH_PELANGGAN$PATH_ID_PELANGGAN"
    const val URL_PELANGGAN_INSERT = "$PATH_API$PATH_PELANGGAN$PATH_INSERT_DATA"
    const val URL_PELANGGAN_UPDATE = "$PATH_API$PATH_PELANGGAN$PATH_UPDATE$PATH_ID_PELANGGAN"
    const val URL_PELANGGAN_DELETE = "$PATH_API$PATH_PELANGGAN$PATH_DELETE"

    const val URL_TUKANG_GET_BY_NILAI = "$PATH_API$PATH_NILAI"
    const val URL_TUKANG_GET = "$PATH_API$PATH_TUKANG"
    const val URL_TUKANG_GET_BY_ID = "$PATH_API$PATH_TUKANG$PATH_ID_TUKANG"
    const val URL_TUKANG_INSERT = "$PATH_API$PATH_TUKANG$PATH_INSERT_DATA"
    const val URL_TUKANG_UPDATE = "$PATH_API$PATH_TUKANG$PATH_UPDATE$PATH_ID_TUKANG"
    const val URL_TUKANG_DELETE = "$PATH_API$PATH_TUKANG$PATH_DELETE"

    const val URL_PESANAN_GET = "$PATH_API$PATH_PESANAN"
    const val URL_PESANAN_GET_BY_ID = "$PATH_API$PATH_PESANAN$PATH_ID_PESANAN"
    const val URL_PESANAN_GET_BY_PELANGGAN = "$PATH_API$PATH_PESANAN$PATH_PELANGGAN$PATH_ID_PELANGGAN"
    const val URL_PESANAN_GET_BY_TUKANG = "$PATH_API$PATH_PESANAN$PATH_TUKANG$PATH_ID_TUKANG"
    const val URL_PESANAN_INSERT = "$PATH_API$PATH_PESANAN$PATH_INSERT_DATA"
    const val URL_PESANAN_UPDATE = "$PATH_API$PATH_PESANAN$PATH_UPDATE$PATH_ID_PESANAN"
    const val URL_PESANAN_DELETE = "$PATH_API$PATH_PESANAN$PATH_DELETE$PATH_ID_PESANAN"

    const val URL_RATING_GET = "$PATH_API$PATH_RATING"
    const val URL_RATING_INSERT = "$PATH_API$PATH_RATING$PATH_INSERT_DATA"
    const val URL_RATING_UPDATE = "$PATH_API$PATH_RATING$PATH_UPDATE"
    const val URL_RATING_DELETE = "$PATH_API$PATH_RATING$PATH_DELETE"

    const val URL_UKURAN_GET = "$PATH_API$PATH_UKURAN"
    const val URL_UKURAN_INSERT = "$PATH_API$PATH_UKURAN$PATH_INSERT_DATA"
    const val URL_UKURAN_UPDATE = "$PATH_API$PATH_UKURAN$PATH_UPDATE"
    const val URL_UKURAN_DELETE = "$PATH_API$PATH_UKURAN$PATH_DELETE"

    const val URL_UTILITAS_GET = "$PATH_API$PATH_UTILITAS"
    const val URL_UTILITAS_INSERT = "$PATH_API$PATH_UTILITAS$PATH_INSERT_DATA"
    const val URL_UTILITAS_UPDATE = "$PATH_API$PATH_UTILITAS$PATH_UPDATE"
    const val URL_UTILITAS_DELETE = "$PATH_API$PATH_DETAIL_KATEGORI$PATH_DELETE"

    const val URL_UKURAN_DETAIL_KATEGORI_GET = "$PATH_API$PATH_UKURAN_DETAIL_KATEGORI"
    const val URL_UKURAN_DETAIL_KATEGORI_GET_BY_DETAIL_KATEGORI = "$PATH_API$PATH_UKURAN_DETAIL_KATEGORI$PATH_GET_DETAIL_KATEGORI$PATH_ID_DETAIL_KATEGORI"
    const val URL_UKURAN_DETAIL_KATEGORI_INSERT = "$PATH_API$PATH_UKURAN_DETAIL_KATEGORI$PATH_INSERT_DATA"
    const val URL_UKURAN_DETAIL_KATEGORI_UPDATE = "$PATH_API$PATH_UKURAN_DETAIL_KATEGORI$PATH_UPDATE"
    const val URL_UKURAN_DETAIL_KATEGORI_DELETE = "$PATH_API$PATH_UKURAN_DETAIL_KATEGORI$PATH_DELETE$PATH_ID_UKURAN_DETAIL_KATEGORI"

    const val URL_UKURAN_DETAIL_PESANAN_GET = "$PATH_API$PATH_UKURAN_DETAIL_PESANAN"
    const val URL_UKURAN_DETAIL_PESANAN_GET_BY_PESANAN = "$PATH_API$PATH_UKURAN_DETAIL_PESANAN$PATH_PESANAN$PATH_ID_PESANAN"
    const val URL_UKURAN_DETAIL_PESANAN_INSERT = "$PATH_API$PATH_UKURAN_DETAIL_PESANAN$PATH_INSERT_DATA"
    const val URL_UKURAN_DETAIL_PESANAN_UPDATE = "$PATH_API$PATH_UKURAN_DETAIL_PESANAN$PATH_UPDATE$PATH_ID_UKURAN_DETAIL_PESANAN"
    const val URL_UKURAN_DETAIL_PESANAN_DELETE = "$PATH_API$PATH_UKURAN_DETAIL_PESANAN$PATH_DELETE$PATH_ID_UKURAN_DETAIL_PESANAN"

}